import Navbar from "./Navbar";
import Hero from "./Hero";
import LatestCollections from "./LatestCollections";
import Title from "./Title";
import ProductItem from "./ProductItem";
import BestSeller from "./BestSeller";
import OurPolicy from "./OurPolicy";
import NewsLetterBox from "./NewsLetterBox";
import Footer from "./Footer";
import Collections from "./Collections";
import SearchBar from "./SearchBar";
import RelatedProducts from "./RelatedProducts";
import CartTotal from "./CartTotal";
export { Navbar , Hero , LatestCollections , Title , ProductItem , BestSeller , OurPolicy , NewsLetterBox , Footer , Collections , SearchBar , RelatedProducts , CartTotal}; ; 